print("hello Everyone") 
city_name=input("Which city did you grow up\n")
pet_name=input("Whats your pet name\n")
print(city_name + pet_name)
print("your band name is" + " " + city_name + pet_name)

print("hello Everyone") 
city_name=input("Which city did you grow up\n")
pet_name=input("Whats your pet name\n")
print(city_name + pet_name)
print("your band name is" + " " + city_name + pet_name)
